config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'

  devise_for :users
  root to: 'pages#index'

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end

  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
    resources :messages, only: [:create]
    resources :submissions, only: [:create] do
      put 'confirm'
      put 'decline'
    end

    get 'submit/:match_id', to: 'submissions#submit', as: :submit_match
    get 'messages/new/:nickname', to: 'messages#new', as: :send_message
  end

  get 'profile/:slug', to: 'profiles#show', as: :profile
  get 'messages', to: 'thredded/private_topics#index', as: :messages

  get 'contacts', to: 'pages#contacts'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :players, class_name: 'User'
  has_many :groups

  mount_uploader :avatar, AvatarUploader

  scope :sorted_by_priority, -> { all.sort {|a, b| a.status_index <=> b.status_index } }
  after_save :generate_groups, if: -> { groups.empty? && max_players == players.count }

  STATUSES = ['Live', 'Scheduled', 'Finished']

  def status
    return 'Finished' if winner

    if max_players == players.count || Time.current > end_registration_date
      'Live'
    else
      'Scheduled'
    end
  end

  def category
    'Poker'
  end

  def status_index
    STATUSES.index(status)
  end

  def winner
    false
  end

  def generate_groups
    tournament_players = self.players.shuffle

    group_count = tournament_players.count / self.players_per_group
    label = 'A'

    (0...group_count).each do |i|
      group = self.groups.create!(label: label)

      tournament_players[(i * players_per_group)...(i * players_per_group + players_per_group)].each do |player|
        group.players << player
      end

      group.save
      label = label.next
    end
  end
end

app/controllers/dashboard/messages_controller.rb
module Dashboard
  class MessagesController < ApplicationController
    before_action :authenticate_user!

    def new
      @oponent_nickname = params[:nickname]

      respond_to do |format|
        format.html
        format.js
      end
    end

    def create
      controller = Thredded::PrivateTopicsController.new
      controller.request = request
      controller.response = response
      controller.create

      redirect_to dashboard_tournament_path(current_user.tournaments.last), notice: 'Сообщения успешно отправлено!'
    end
  end
end

app/controllers/dashboard/submissions_controller.rb
module Dashboard
  class SubmissionsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_permission, except: [:confirm, :decline]

    def submit
      respond_to do |format|
        format.html
        format.js
      end
    end

    def create
      @submission = Submission.create!(match_id: params[:submission][:match_id], win: ActiveModel::Type::Boolean.new.cast(params[:submission][:win]), proof: params[:submission][:proof], user_id: current_user.id)

      redirect_to dashboard_tournament_path(@submission.match.group.tournament), notice: 'Отправлено! Ожидается подтверждения противника.'
    end

    def confirm
      @submission = Submission.find(params[:submission_id])
      @submission.submitted!

      redirect_to dashboard_tournament_path(@submission.match.group.tournament), notice: 'Данные внесены в таблицу!'
    end

    def decline
      @submission = Submission.find(params[:submission_id])
      @submission.declined!

      redirect_to dashboard_tournament_path(@submission.match.group.tournament), alert: 'Результат отклонен!'
    end

    private

    def check_permission
      @match = Match.find(params[:match_id] || params[:submission][:match_id])

      raise CanCan::AccessDenied unless @match.players_include?(current_user.id)
    end
  end
end

app/controllers/dashboard/tournaments_controller.rb
module Dashboard
  require 'will_paginate/array'

  class TournamentsController < ApplicationController
    before_action :authenticate_user!

    def index
      @tournaments = current_user.tournaments.sorted_by_priority.paginate(page: params[:page], per_page: 12)
    end

    def show
      @tournament = current_user.tournaments.friendly.find(params[:id])

      label = 'A'
      @tournament.groups.includes(:players).each do |group|
        label = group.label if group.players.pluck(:id).include?(current_user.id)
      end

      if @tournament.groups.any?
        @group = @tournament.groups.find_by!(label: params['group'] || label)
        @another_groups = @tournament.groups.where.not(label: @group&.label).pluck(:label)
      end
    end
  end
end

app/controllers/tournaments_controller.rb
require 'will_paginate/array'

class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: [:register_player]

  def index
    @tournaments = Tournament.sorted_by_priority.paginate(page: params[:page], per_page: 12)
  end

  def show
    @tournament = Tournament.friendly.find(params[:id])
  end

  def register_player
    @tournament = Tournament.friendly.find(params[:tournament_id])

    if @tournament.players.count >= (@tournament.max_players || 9999)
      redirect_to @tournament, alert: 'Достигнуто максимальное количество участников!'
    elsif @tournament.players.include?(current_user)
      redirect_to @tournament, alert: 'Вы уже зарегистрировались в турнире!'
    else
      @tournament.players << current_user
      @tournament.save

      redirect_to dashboard_tournament_path(@tournament), notice: 'Вы успешно зарегистрировались в турнире!'
    end
  end
end

app/views/dashboard/tournaments/index.html.haml
%h2.card.card.body.text-center.mb-4.py-1
  Зарегистрирован в турнирах:
- if @tournaments.count == 0
  %h4.text-center.mt-5
    Список пуст...
  .text-center
    = link_to 'Перейти к списку всех турниров', tournaments_path
.row
  - @tournaments.each do |tournament|
    .col-3.mb-3
      = link_to dashboard_tournament_path(tournament), class: 'custom-card' do
        .card.tournament-card
          - if tournament.avatar.path
            = image_tag tournament.avatar.card.url
          - else
            = image_tag '/rsz_default-tournament.png'
          .card-body.tournament-body
            .category
              = tournament.category
            %span.tournament-name
              = tournament.name
            .row.mt-4
              .col-4
                .tournament-status
                  %div{ class:[ (:status_live if tournament.status == 'Live'), (:status_scheduled if tournament.status == 'Scheduled'), (:status_finished if tournament.status == 'Finished') ] }
                    = tournament.status
              .col-8
                %p.text-right.prize
                  = "$#{tournament.prize_fund}"
.row
  .col-2.mx-auto
    = will_paginate @tournaments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/dashboard/tournaments/show.html.haml
#modal-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
.row.ml-2
  .col-2
    %span.tournament-name
      = @tournament.name
  .col-2
    %span.ml-2.tournament-show-status
      = @tournament.status
  .col-3
    %span.ml-2
      %span.font-weight-bold Пароль турнира:
      = " #{@tournament.password}"
  .col-5
    %p.text-right.mr-2.start-at
      = "Начало: #{@tournament.end_registration_date.strftime("%d-%m-%Y / %H:%M")}"
  .col-12.tournament-image
    = image_tag @tournament.avatar.tournament_show.url
  - if @tournament.groups.empty?
    .col-4.mt-3
      %table.table
        %thead.thead-dark
          %tr
            %th{:scope => "col"} #
            %th{:scope => "col"} Cписок участников
        %tbody
          - @tournament.players.each do |player|
            %tr
              %th{:scope => "row"}
                = @tournament.players.index(player) + 1
              %td
                = player.nickname
  - else
    .col-12.mt-3
      %select{:onchange => "this.options[this.selectedIndex].value  (window.location = this.options[this.selectedIndex].value);"}
        %option{:value => ""}
          = "Выбрать группу..."
        - @another_groups.each do |label|
          %option{:value => dashboard_tournament_path(@tournament, group: label)}
            = "Группа #{label}"
    .col-6.mt-3
      %table.table
        %thead.thead-dark
          %tr
            %th{:scope => "col"} #
            %th{:scope => "col"}
              = "Группа #{@group.label}"
            %th{:scope => "col"} Матчи
            %th{:scope => "col"} Выиграл
            %th{:scope => "col"} Проиграл
            %th{:scope => "col"} Очки
        %tbody
          - @group.sorted_players.each_with_index do |player, index|
            - all_matches = @group.matches.submitted_matches.select { |m| m.players_include?(player.id) }.size
            - won_matches = @group.matches.submitted_matches.where(winner_id: player.id).size
            %tr{class: "#{'font-weight-bold' if player.id == current_user.id}"}
              %th{:scope => "row"}
                = index + 1
              %td
                = player.nickname
              %td
                = all_matches
              %td
                = won_matches
              %td
                = (all_matches - won_matches)
              %td
                = won_matches

    .col-6.mt-3
      %h3.card.card.body.text-center.mb-0.py-2
        = "Матчи группы #{@group.label}"
      %table.table
        %tbody
          - @group.matches.each do |match|
            %tr.mx-auto
              %td{class: "text-center #{'bg-success' if match.winner_id == match.players.first.id}"}
                - if match.players.first.id != current_user.id && match.players_include?(current_user.id) && match.winner_id.nil?
                  = link_to dashboard_send_message_path(nickname: match.versus_user(current_user.id).nickname),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do
                    %i.fa.fa-pencil-square-o
                = link_to match.players.first.nickname, profile_path(slug: match.players.first.nickname), { :target => '_blank' }
              %td.text-center
                - if match.winner_id == match.players.first.id
                  = "1 : "
                - else
                  = "0 : "
                - if match.winner_id == match.players.last.id
                  = 1
                - else
                  = 0
              %td{class: "text-center #{'bg-success' if match.winner_id == match.players.last.id}"}
                - if match.players.last.id != current_user.id && match.players_include?(current_user.id) && match.winner_id.nil?
                  = link_to dashboard_send_message_path(nickname: match.versus_user(current_user.id).nickname),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do
                    %i.fa.fa-pencil-square-o
                = link_to match.players.last.nickname, profile_path(slug: match.players.last.nickname), { :target => '_blank' }
              - if match.players_include?(current_user.id) && match.winner_id.nil? && !match.sended?
                %td.text-right.pr-0
                  = link_to 'Внести результат', dashboard_submit_match_path(match_id: match.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', 'class' => 'btn btn-warning'}
    - if @group.sended_matches(current_user.id).any?
      .col-6.mt-3.mb-4
        %h3.card.card.body.text-center.mb-0.py-2
          = "Неподтвержденные результаты"
        %table.table
          %tbody
            - @group.sended_matches(current_user.id).each do |match|
              %tr.mx-auto
                %td
                  = link_to current_user.nickname, profile_path(slug: current_user.nickname), { :target => '_blank' }
                %td.text-center
                  - if match.submissions.last.win
                    = "0 : 1"
                  - else
                    = "1 : 0"
                %td{class: 'text-right'}
                  = link_to match.versus_user(current_user.id).nickname, profile_path(slug: match.versus_user(current_user).nickname), { :target => '_blank' }
                %td.text-right.pr-0
                  = link_to 'Confirm', dashboard_submission_confirm_path(match.submissions.last), class: 'btn btn-success', data: {confirm: "Are you sure?"}, method: :put
                %td.text-right.pr-0
                  = link_to 'Decline', dashboard_submission_decline_path(match.submissions.last), class: 'btn btn-danger', data: {confirm: "Are you sure?"}, method: :put