config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'

  devise_for :users
  root to: 'pages#index'

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end

  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
    resources :messages, only: [:create]
    resources :submissions, only: [:create] do
      put 'confirm'
      put 'decline'
    end

    get 'submit/:match_id', to: 'submissions#submit', as: :submit_match
    get 'messages/new/:nickname', to: 'messages#new', as: :send_message
  end

  get 'profile/:slug', to: 'profiles#show', as: :profile
  get 'messages', to: 'thredded/private_topics#index', as: :messages

  get 'contacts', to: 'pages#contacts'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :players, class_name: 'User'
  has_many :groups

  mount_uploader :avatar, AvatarUploader

  scope :sorted_by_priority, -> { all.sort {|a, b| a.status_index <=> b.status_index } }
  after_save :generate_groups, if: -> { groups.empty? && max_players == players.count }

  STATUSES = ['Live', 'Scheduled', 'Finished']

  def status
    return 'Finished' if winner

    if max_players == players.count || Time.current > end_registration_date
      'Live'
    else
      'Scheduled'
    end
  end

  def category
    'Poker'
  end

  def status_index
    STATUSES.index(status)
  end

  def winner
    false
  end

  def generate_groups
    tournament_players = self.players.shuffle

    group_count = tournament_players.count / self.players_per_group
    label = 'A'

    (0...group_count).each do |i|
      group = self.groups.create!(label: label)

      tournament_players[(i * players_per_group)...(i * players_per_group + players_per_group)].each do |player|
        group.players << player
      end

      group.save
      label = label.next
    end
  end
end

app/controllers/dashboard/tournaments_controller.rb
module Dashboard
  require 'will_paginate/array'

  class TournamentsController < ApplicationController
    before_action :authenticate_user!

    def index
      @tournaments = current_user.tournaments.sorted_by_priority.paginate(page: params[:page], per_page: 12)
    end

    def show
      @tournament = current_user.tournaments.friendly.find(params[:id])

      label = 'A'
      @tournament.groups.includes(:players).each do |group|
        label = group.label if group.players.pluck(:id).include?(current_user.id)
      end

      if @tournament.groups.any?
        @group = @tournament.groups.find_by!(label: params['group'] || label)
        @another_groups = @tournament.groups.where.not(label: @group&.label).pluck(:label)
      end
    end
  end
end

app/controllers/tournaments_controller.rb
require 'will_paginate/array'

class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: [:register_player]

  def index
    @tournaments = Tournament.sorted_by_priority.paginate(page: params[:page], per_page: 12)
  end

  def show
    @tournament = Tournament.friendly.find(params[:id])
  end

  def register_player
    @tournament = Tournament.friendly.find(params[:tournament_id])

    if @tournament.players.count >= (@tournament.max_players || 9999)
      redirect_to @tournament, alert: 'Достигнуто максимальное количество участников!'
    elsif @tournament.players.include?(current_user)
      redirect_to @tournament, alert: 'Вы уже зарегистрировались в турнире!'
    else
      @tournament.players << current_user
      @tournament.save

      redirect_to dashboard_tournament_path(@tournament), notice: 'Вы успешно зарегистрировались в турнире!'
    end
  end
end

app/views/tournaments/index.html.haml
.row
  - @tournaments.each do |tournament|
    .col-3.mb-3
      = link_to tournament_path(tournament), class: 'custom-card' do
        .card.tournament-card
          - if tournament.avatar.path
            = image_tag tournament.avatar.card.url
          - else
            = image_tag '/rsz_default-tournament.png'
          .card-body.tournament-body
            .category
              = tournament.category
            %span.tournament-name
              = tournament.name
            .row.mt-4
              .col-4
                .tournament-status
                  %div{ class:[ (:status_live if tournament.status == 'Live'), (:status_scheduled if tournament.status == 'Scheduled'), (:status_finished if tournament.status == 'Finished') ] }
                    = tournament.status
              .col-8
                %p.text-right.prize
                  = "$#{tournament.prize_fund}"
.row
  .col-2.mx-auto
    = will_paginate @tournaments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/tournaments/show.html.haml
.row.ml-2
  .col-2
    %span.tournament-name
      = @tournament.name
  .col-2
    %span.ml-2.tournament-show-status
      = @tournament.status
  .col-8
    %p.text-right.mr-2.start-at
      = "Начало: #{@tournament.end_registration_date.strftime("%d-%m-%Y / %H:%M")}"
  .col-12.tournament-image
    = image_tag @tournament.avatar.tournament_show.url
  .col-8.mt-3
    %h4 Информация о турнире:
    %ul
      %li
        Максимальное количество участников:
        %strong
          - if @tournament.max_players
            = @tournament.max_players
          - else
            = 'неограниченно'
      %li
        Призовой фонд:
        %strong
          = "$#{@tournament.prize_fund}"
      %li
        %strong
          = @tournament.next_stage_length || 8
        лучших игроков попадают в финальную стадию турнира
    - if @tournament.rules
      %h4 Правила:
      %p
        = @tournament.rules.html_safe

  - if @tournament.status == 'Scheduled'
    .col-4.mt-3
      - if @tournament.max_players
        %h4.text-right
          Свободных мест:
          = @tournament.max_players - @tournament.players.size
      - if current_user && !@tournament.players.include?(current_user) && (@tournament.max_players || 99999) > @tournament.players.size
        .text-right
          = button_to "Зарегистрироваться", tournament_register_player_path(@tournament), method: :put, class: 'btn btn-success btn-lg', data: { confirm: "Are you sure?" }