config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'

  devise_for :users
  root to: 'pages#index'

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end

  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
    resources :messages, only: [:create]
    resources :submissions, only: [:create] do
      put 'confirm'
      put 'decline'
    end

    get 'submit/:match_id', to: 'submissions#submit', as: :submit_match
    get 'messages/new/:nickname', to: 'messages#new', as: :send_message
  end

  get 'profile/:slug', to: 'profiles#show', as: :profile
  get 'messages', to: 'thredded/private_topics#index', as: :messages

  get 'contacts', to: 'pages#contacts'
end

app/views/shared/_flash_messages.haml
- if notice
  .alert.alert-info
    %a.close{ "data-dismiss" => "alert",  "href" => "#" } x
    %ul.mb-0
      %li
        = notice
- if alert
  .alert.alert-warning
    %a.close{ "data-dismiss" => "alert",  "href" => "#" } x
    %ul.mb-0
      %li
        = alert

app/views/shared/_footer.haml
%footer.page-footer.py-2.bg-dark.fixed-bottom
  .container
    %p.m-0.text-center.text-white Copyright © GShow 2019

app/views/shared/_navbar.haml
%nav.navbar.navbar-expand-lg.fixed-top.navbar-dark.bg-dark
  .container
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.navbar-nav.ml-0
        %li.nav-item
          = link_to image_tag('/logo.png'), main_app.root_path, class: 'nav-link'
        %li.nav-item.navbar-text.nav-font-family
          = link_to 'Турниры'.upcase, main_app.tournaments_path, class: "nav-link #{'active-nav' if current_page?(main_app.tournaments_path)}"
        %li.nav-item.navbar-text.nav-font-family
          = link_to 'Новости'.upcase, main_app.articles_path, class: "nav-link #{'active-nav' if articles_path?}"
        %li.nav-item.navbar-text.nav-font-family
          = link_to 'Стримы игроков'.upcase, main_app.streams_path, class: "nav-link #{'active-nav' if current_page?(main_app.streams_path)}"
        %li.nav-item.navbar-text.nav-font-family
          = link_to 'Форум'.upcase, main_app.thredded_path, class: "nav-link #{'active-nav' if forum_path?}"
        %li.nav-item.navbar-text.nav-font-family
          = link_to 'Контакты'.upcase, main_app.contacts_path, class: "nav-link #{'active-nav' if current_page?(main_app.contacts_path)}"
    %ul.navbar-nav.navbar-right.mr-0
      - if current_user
        %li.nav-item.nav-font-family
          = link_to 'Личные сообщения'.upcase, main_app.messages_path, class: "nav-link #{'active-nav' if messages_path?}"
        %li.nav-item.nav-font-family
          = link_to 'Игровой кабинет'.upcase, main_app.dashboard_tournaments_path, class: "nav-link #{'active-nav' if dashboard_path?}"
        %li.dropdown.ml-2.nav-nickname
          %a.dropdown-toggle{'data-toggle': 'dropdown', href: '#'}
            = current_user.nickname
            %b.caret
          %ul.dropdown-menu.nav-black
            %li.nav-font-family= link_to 'Настройки', main_app.edit_user_registration_path, class: 'nav-link'
            %li.nav-font-family= link_to 'Профиль', main_app.profile_path(slug: current_user.nickname), class: 'nav-link'
            %li.nav-font-family= link_to 'Выйти', main_app.destroy_user_session_path, class: 'nav-link', "data-method" => :delete
      - else
        %li.nav-item.nav-font-family
          %a{href: main_app.new_user_session_path, class: "nav-link #{'active-nav' if current_page?(main_app.new_user_session_path)}"} ВХОД
        %li.nav-item.nav-font-family
          %a{href: main_app.new_user_registration_path, class: "nav-link #{'active-nav' if current_page?(main_app.new_user_registration_path)}"} РЕГИСТРАЦИЯ